baseURL = "https://dwins.xyz/"
languageCode = "en-us"
title = "David Winslow"

[params]
Description = "Solving problems with computers."
SidebarListLimit = 3

[[params.ExternalLinks]]
    label = "Github"
    href = "https://github.com/dwins"

[taxonomies]